<?php

// ==========================================================================
// Code generated by module:gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use App\Http\Middleware\Auth;
use App\Modules\Admin\Middleware\Privilege;
use Illuminate\Support\Facades\Route;

// admin route start
Route::prefix('admin')->middleware([Auth::class, Privilege::class])->group(function () {
    // 显示列表页面
    Route::get('department', [\App\Modules\Admin\Controllers\DepartmentController::class, 'index'])->name('department');
    // 新增表单页面
    Route::get('department/create', [\App\Modules\Admin\Controllers\DepartmentController::class, 'create'])->name('department.create');
    // 编辑表单页面
    Route::get('department/edit', [\App\Modules\Admin\Controllers\DepartmentController::class, 'edit'])->name('department.edit');
    // 查询列表接口
    Route::post('department/query', [\App\Modules\Admin\Controllers\DepartmentController::class, 'query']);
    // 新增接口
    Route::post('department/store', [\App\Modules\Admin\Controllers\DepartmentController::class, 'store']);
    // 获取详情接口
    Route::get('department/show', [\App\Modules\Admin\Controllers\DepartmentController::class, 'show'])->name('department.show');
    // 更新接口
    Route::put('department/update', [\App\Modules\Admin\Controllers\DepartmentController::class, 'update']);
    // 删除接口
    Route::delete('department/destroy', [\App\Modules\Admin\Controllers\DepartmentController::class, 'destroy']);
    // 显示列表页面
    Route::get('permission', [\App\Modules\Admin\Controllers\PermissionController::class, 'index'])->name('permission');
    // 新增表单页面
    Route::get('permission/create', [\App\Modules\Admin\Controllers\PermissionController::class, 'create'])->name('permission.create');
    // 编辑表单页面
    Route::get('permission/edit', [\App\Modules\Admin\Controllers\PermissionController::class, 'edit'])->name('permission.edit');
    // 查询列表接口
    Route::post('permission/query', [\App\Modules\Admin\Controllers\PermissionController::class, 'query']);
    // 新增接口
    Route::post('permission/store', [\App\Modules\Admin\Controllers\PermissionController::class, 'store']);
    // 获取详情接口
    Route::get('permission/show', [\App\Modules\Admin\Controllers\PermissionController::class, 'show'])->name('permission.show');
    // 更新接口
    Route::put('permission/update', [\App\Modules\Admin\Controllers\PermissionController::class, 'update']);
    // 删除接口
    Route::delete('permission/destroy', [\App\Modules\Admin\Controllers\PermissionController::class, 'destroy']);
    // 显示列表页面
    Route::get('role', [\App\Modules\Admin\Controllers\RoleController::class, 'index'])->name('role');
    // 新增表单页面
    Route::get('role/create', [\App\Modules\Admin\Controllers\RoleController::class, 'create'])->name('role.create');
    // 编辑表单页面
    Route::get('role/edit', [\App\Modules\Admin\Controllers\RoleController::class, 'edit'])->name('role.edit');
    // 查询列表接口
    Route::post('role/query', [\App\Modules\Admin\Controllers\RoleController::class, 'query']);
    // 新增接口
    Route::post('role/store', [\App\Modules\Admin\Controllers\RoleController::class, 'store']);
    // 获取详情接口
    Route::get('role/show', [\App\Modules\Admin\Controllers\RoleController::class, 'show'])->name('role.show');
    // 更新接口
    Route::put('role/update', [\App\Modules\Admin\Controllers\RoleController::class, 'update']);
    // 删除接口
    Route::delete('role/destroy', [\App\Modules\Admin\Controllers\RoleController::class, 'destroy']);
    // 显示列表页面
    Route::get('rolePermission', [\App\Modules\Admin\Controllers\RolePermissionController::class, 'index'])->name('rolePermission');
    // 新增表单页面
    Route::get('rolePermission/create', [\App\Modules\Admin\Controllers\RolePermissionController::class, 'create'])->name('rolePermission.create');
    // 编辑表单页面
    Route::get('rolePermission/edit', [\App\Modules\Admin\Controllers\RolePermissionController::class, 'edit'])->name('rolePermission.edit');
    // 查询列表接口
    Route::post('rolePermission/query', [\App\Modules\Admin\Controllers\RolePermissionController::class, 'query']);
    // 新增接口
    Route::post('rolePermission/store', [\App\Modules\Admin\Controllers\RolePermissionController::class, 'store']);
    // 获取详情接口
    Route::get('rolePermission/show', [\App\Modules\Admin\Controllers\RolePermissionController::class, 'show'])->name('rolePermission.show');
    // 更新接口
    Route::put('rolePermission/update', [\App\Modules\Admin\Controllers\RolePermissionController::class, 'update']);
    // 删除接口
    Route::delete('rolePermission/destroy', [\App\Modules\Admin\Controllers\RolePermissionController::class, 'destroy']);
    // 显示列表页面
    Route::get('subsidiary', [\App\Modules\Admin\Controllers\SubsidiaryController::class, 'index'])->name('subsidiary');
    // 新增表单页面
    Route::get('subsidiary/create', [\App\Modules\Admin\Controllers\SubsidiaryController::class, 'create'])->name('subsidiary.create');
    // 编辑表单页面
    Route::get('subsidiary/edit', [\App\Modules\Admin\Controllers\SubsidiaryController::class, 'edit'])->name('subsidiary.edit');
    // 查询列表接口
    Route::post('subsidiary/query', [\App\Modules\Admin\Controllers\SubsidiaryController::class, 'query']);
    // 新增接口
    Route::post('subsidiary/store', [\App\Modules\Admin\Controllers\SubsidiaryController::class, 'store']);
    // 获取详情接口
    Route::get('subsidiary/show', [\App\Modules\Admin\Controllers\SubsidiaryController::class, 'show'])->name('subsidiary.show');
    // 更新接口
    Route::put('subsidiary/update', [\App\Modules\Admin\Controllers\SubsidiaryController::class, 'update']);
    // 删除接口
    Route::delete('subsidiary/destroy', [\App\Modules\Admin\Controllers\SubsidiaryController::class, 'destroy']);
    // 显示列表页面
    Route::get('user', [\App\Modules\Admin\Controllers\UserController::class, 'index'])->name('user');
    // 新增表单页面
    Route::get('user/create', [\App\Modules\Admin\Controllers\UserController::class, 'create'])->name('user.create');
    // 编辑表单页面
    Route::get('user/edit', [\App\Modules\Admin\Controllers\UserController::class, 'edit'])->name('user.edit');
    // 查询列表接口
    Route::post('user/query', [\App\Modules\Admin\Controllers\UserController::class, 'query']);
    // 新增接口
    Route::post('user/store', [\App\Modules\Admin\Controllers\UserController::class, 'store']);
    // 获取详情接口
    Route::get('user/show', [\App\Modules\Admin\Controllers\UserController::class, 'show'])->name('user.show');
    // 更新接口
    Route::put('user/update', [\App\Modules\Admin\Controllers\UserController::class, 'update']);
    // 删除接口
    Route::delete('user/destroy', [\App\Modules\Admin\Controllers\UserController::class, 'destroy']);
    // 显示列表页面
    Route::get('userRole', [\App\Modules\Admin\Controllers\UserRoleController::class, 'index'])->name('userRole');
    // 新增表单页面
    Route::get('userRole/create', [\App\Modules\Admin\Controllers\UserRoleController::class, 'create'])->name('userRole.create');
    // 编辑表单页面
    Route::get('userRole/edit', [\App\Modules\Admin\Controllers\UserRoleController::class, 'edit'])->name('userRole.edit');
    // 查询列表接口
    Route::post('userRole/query', [\App\Modules\Admin\Controllers\UserRoleController::class, 'query']);
    // 新增接口
    Route::post('userRole/store', [\App\Modules\Admin\Controllers\UserRoleController::class, 'store']);
    // 获取详情接口
    Route::get('userRole/show', [\App\Modules\Admin\Controllers\UserRoleController::class, 'show'])->name('userRole.show');
    // 更新接口
    Route::put('userRole/update', [\App\Modules\Admin\Controllers\UserRoleController::class, 'update']);
    // 删除接口
    Route::delete('userRole/destroy', [\App\Modules\Admin\Controllers\UserRoleController::class, 'destroy']);
});
// end
