<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// Route start
Route::prefix('api/user')->middleware('api')->group(function () {
});
// end
